### PR TITLE
Coq type safety

### PR DESCRIPTION
**Pull request by DIJamner**
Add proofs of progress and preservation for BIL. Note that the definition of `let` bindings has been altered to facilitate the proofs. It should be possible to demonstrate that this version works the same way as the master branch by a bisimulation argument, if this difference is a concern.

### CODE REVIEW

**Comment by ivg** [comment]
It looks like that one of the rebased and merged commit happen to be in this branch, so we have a conflict now. 

Besides, if this rebasing workflow makes your life harder I can just do plain old merge commits. I just prefer to have a linear history :)

**Comment by DIJamner** [comment]
Looking at the commit history, it appears that I made the last set of changes a little messy since I was changing both this branch and master in parallel. The commits seem to be a bit awkwardly interleaved, so at a glance I am not sure the best way to straighten them out. I know it makes the history a little less clear, but as long as the `coq-formalization` branch ends up matching my `coq_type_safety` branch, it should be correct at least.

I am no longer working on the project that motivated this work, so I unfortunately don't have much time to straighten things out. If you see a simple way for me to clean it up, I would be happy to repeat it in my branch if that would make things cleaner. Otherwise, I'm afraid I have to leave things as is for now.

**Comment by ccasin** [comment]
I'm happy to squash this PR into a single commit with clean diffs against the current upstream coq-formalization branch, if that's preferred.

**Comment by ivg** [comment]
The good news is that only rebasing doesn't work while squashing and the plain old merge commit works fine. I'm creating a merge commit, otherwise, we may break someone's work branch. We may squash it, if necessary when we will merge it into the master branch.

**Pull request merged**
